version: 2

project_name: pushman

builds:
  - id: pushman
    main: ./cmd/pushman
    binary: pushman
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm64
    flags:
      - -trimpath
    ldflags:
      - >-
        -s -w
        -X main.version={{.Version}}
        -X main.commit={{.Commit}}
        -X main.date={{.Date}}

archives:
  - id: archives
    ids: [pushman]
    formats: [tar.gz]
    format_overrides:
      - goos: windows
        formats: [zip]
    name_template: >-
      {{ .ProjectName }}_{{ .Version }}_
      {{- if eq .Os "darwin" }}macOS{{ else }}{{ .Os }}{{ end }}_
      {{- if eq .Arch "amd64" }}x86_64{{ else }}{{ .Arch }}{{ end }}

checksum:
  name_template: checksums.txt
  extra_files:
    - glob: windows-dist/*_setup.exe
    - glob: windows-dist/*_winget.zip

changelog:
  use: github-native

release:
  prerelease: auto
  draft: true
  extra_files:
    - glob: windows-dist/*_setup.exe
    - glob: windows-dist/*_winget.zip
